language: csharp 
dist: trusty
os: linux
mono: none
dotnet: 2.1.4
services:
- docker
before_install:
- npm install -g npm
install:
- dotnet restore ./angular5dotnetcore2.0/dotnetcoreplusangular5Template.sln
script:
 - dotnet --info
 - dotnet build ./angular5dotnetcore2.0/dotnetcoreplusangular5Template.sln
 - ls -a
 - chmod +x build.sh && bash build.sh
after_success:
 - docker login -u $Docker_UserName -p $Docker_Password
 - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
   docker tag $Docker_Repo:$TAG $Docker_Repo:$TRAVIS_BUILD_NUMBER;
   docker push $Docker_Repo:$TRAVIS_BUILD_NUMBER;
   fi 
 - docker push $Docker_Repo:$Tag
