language: csharp 
dist: trusty
os: linux
mono: none
dotnet: 2.1.4
services:
- docker
before_install:
- npm install -g npm    
install:
- dotnet restore ./angular5dotnetcore2.0/dotnetcoreplusangular5Template.sln
script:
 - dotnet --info
 - dotnet build ./angular5dotnetcore2.0/dotnetcoreplusangular5Template.sln
 - ls -a
 - chmod +x build.sh && bash build.sh
 - docker login -u $Docker_UserName -p $Docker_Password
 - docker build --no-cache -t spartha1995/angular5dotnetcore2.0 .
 - docker tag spartha1995/angular5dotnetcore2.0:latest spartha1995/angular5dotnetcore2.0:v1
 - docker push spartha1995/angular5dotnetcore2.0
