language: csharp  
sudo: required  
dist: trusty 
dotnet: 2.1.4
install:
  - dotnet restore ./angular5dotnetcore2.0/dotnetcoreplusangular5Template.sln
script:
  - dotnet build ./angular5dotnetcore2.0/dotnetcoreplusangular5Template.sln