language: csharp 
dist: trusty
os: linux
mono: none
dotnet: 2.1.4
before_install:
- npm install -g npm
install:
- dotnet restore ./angular5dotnetcore2.0/dotnetcoreplusangular5Template.sln
script:
 - dotnet --info
 - dotnet build ./angular5dotnetcore2.0/dotnetcoreplusangular5Template.sln --configuration release
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/build.sh
  on:
    branch: master