version: 2
jobs:
  build:
    docker:
      - image: spartha1995/dotnetcore-build
      
    steps:
      - checkout 
      - setup_remote_docker
      - run: 
          name: Install NPM
          command: cd ./angular5dotnetcore2.0/dotnetcoreplusangular5Template/AngularApp && npm install && cd ../../../

      - save_cache:
          key: npm-cache-{{ checksum "./angular5dotnetcore2.0/dotnetcoreplusangular5Template/AngularApp/package.json" }}
          paths: ./angular5dotnetcore2.0/dotnetcoreplusangular5Template/AngularApp/node_modules
          
      - run:
          name: Build Project
          command: npm run build --prefix ./angular5dotnetcore2.0/dotnetcoreplusangular5Template/AngularApp     

      - run:
          name: Lint Project
          command: npm run lint --prefix ./angular5dotnetcore2.0/dotnetcoreplusangular5Template/AngularApp
      
      - run:
          name: Deploy to ACR
          command: chmod +x ./deploy.sh && bash deploy.sh


